import nodemailer, { type SendMailOptions } from 'nodemailer';

const smtpUser = (process.env.SMTP_USER || '').trim();
// Hostinger rejects forged or ambiguously formatted From addresses. Use the
// authenticated mailbox itself, while allowing a professional display name
// configured in SMTP_FROM when its address belongs to that mailbox.
const configuredFrom = (process.env.SMTP_FROM || '').trim();
const configuredFromAddress = configuredFrom.match(/<([^>]+)>/)?.[1]?.trim() || configuredFrom;
const safeFrom = smtpUser && configuredFromAddress.toLowerCase() === smtpUser.toLowerCase()
  ? configuredFrom
  : smtpUser
    ? `OB Brokers Team <${smtpUser}>`
    : 'OB Brokers Team <no-reply@osvaldobello.com>';

export const SMTP_CONFIG = {
  host: process.env.SMTP_HOST || 'smtp.hostinger.com',
  port: Number(process.env.SMTP_PORT) || 465,
  secure: (Number(process.env.SMTP_PORT) || 465) === 465,
  auth: {
    user: process.env.SMTP_USER || '',
    pass: process.env.SMTP_PASS || '',
  },
  from: safeFrom,
};

const transport = nodemailer.createTransport(SMTP_CONFIG);

function assertSmtpConfigured() {
  if (!SMTP_CONFIG.auth.user || !SMTP_CONFIG.auth.pass) {
    throw new Error('El correo transaccional no está configurado. Completa SMTP_USER y SMTP_PASS en Production.');
  }
}

// Every application email goes through this single Hostinger transport. Auth
// links are generated by Supabase but delivered from here as well.
export const mailer = {
  sendMail: async (options: SendMailOptions) => {
    assertSmtpConfigured();
    return transport.sendMail(options);
  },
};
const PUBLIC_ASSETS_URL = `${
  process.env.NEXT_PUBLIC_SUPABASE_URL || 'https://whrimmszdeghblbktivp.supabase.co'
}/storage/v1/object/public/public-assets`;
const WHITE_LOGO_URL = `${PUBLIC_ASSETS_URL}/ob-brokers-team/brand/logo-horizontal-white-v2.png`;
const EMAIL_HEADER_COLOR = '#0C094E';

export interface SendMagicLinkOptions {
  to: string;
  name: string;
  magicUrl: string;
}

export interface SendInvitationEmailOptions {
  to: string;
  inviteUrl: string;
  organizationName: string;
  roleLabel: string;
  invitedByName: string;
  expiresAt: string;
}

export interface SendAgencyOnboardingReviewEmailOptions {
  to?: string;
  agencyName: string;
  legalName?: string | null;
  taxId?: string | null;
  legalAddress?: string | null;
  contactEmail: string;
  contactPhone?: string | null;
  representativeName: string;
  representativePhone?: string | null;
  representativeEmail: string;
  reviewUrl: string;
}

export interface SendAccessRequestReceivedEmailOptions {
  to: string;
  fullName: string;
  roleType: string;
  agency?: string | null;
}

export interface SendLeadReportEmailOptions {
  clientEmail?: string | null;
  clientName: string;
  projectName: string;
  developerName: string;
  agencyName: string;
  agentName: string;
  workSummary: string;
  reviewers: string[];
  reviewUrl: string;
}

export interface SendBrokerAccessReviewEmailOptions {
  fullName: string;
  email: string;
  phone: string;
  agency?: string | null;
  roleType: string;
  projectInterest?: string | null;
  message?: string | null;
  reviewUrl: string;
  to?: string;
}

export interface SendOperationalNotificationEmailOptions {
  recipients: string[];
  subject: string;
  title: string;
  message: string;
  actionUrl?: string;
  actionLabel?: string;
}

export interface SendProjectInquiryEmailOptions {
  to: string;
  responsibleRecipients: string[];
  requestType: 'information' | 'site_visit';
  fullName: string;
  phone: string;
  email: string;
  profileLabel: string;
  agencyName?: string | null;
  projectName: string;
  typology?: string | null;
  message?: string | null;
  reference: string;
  projectUrl: string;
}

export async function sendOperationalNotificationEmail({ recipients, subject, title, message, actionUrl, actionLabel = 'Abrir en el CRM' }: SendOperationalNotificationEmailOptions) {
  const to = [...new Set(recipients.map((email) => email.trim().toLowerCase()).filter((email) => /^\S+@\S+\.\S+$/.test(email)))];
  if (!to.length) return;
  const action = actionUrl ? `<p style="margin:24px 0 0"><a href="${escapeHtml(actionUrl)}" style="display:inline-block;background:${EMAIL_HEADER_COLOR};color:#fff;padding:12px 18px;border-radius:9px;text-decoration:none;font-weight:700">${escapeHtml(actionLabel)}</a></p>` : '';
  const html = `<!doctype html><html lang="es"><body style="margin:0;background:#f8fafc;font-family:Arial,sans-serif;color:#0f172a"><main style="max-width:620px;margin:32px auto;background:#fff;border:1px solid #e2e8f0;border-radius:18px;overflow:hidden"><header style="padding:28px 32px;background:${EMAIL_HEADER_COLOR};color:#fff"><h1 style="margin:0;font-size:23px">${escapeHtml(title)}</h1></header><section style="padding:28px 32px;font-size:14px;line-height:1.6"><p style="margin:0">${escapeHtml(message)}</p>${action}</section></main></body></html>`;
  await mailer.sendMail({ from: SMTP_CONFIG.from, to, subject, html });
}

export async function sendProjectInquiryEmail(options: SendProjectInquiryEmailOptions) {
  const customerEmail = options.to.trim().toLowerCase();
  if (!/^\S+@\S+\.\S+$/.test(customerEmail)) throw new Error('El correo del solicitante no es válido.');

  const responsibleRecipients = [...new Set(
    options.responsibleRecipients
      .map((email) => email.trim().toLowerCase())
      .filter((email) => /^\S+@\S+\.\S+$/.test(email) && email !== customerEmail)
  )];
  const isVisit = options.requestType === 'site_visit';
  const title = isVisit ? 'Solicitud de visita al proyecto' : 'Solicitud de información';
  const safe = {
    fullName: escapeHtml(options.fullName),
    phone: escapeHtml(options.phone),
    email: escapeHtml(options.email),
    profile: escapeHtml(options.profileLabel),
    agency: escapeHtml(options.agencyName || 'No aplica'),
    project: escapeHtml(options.projectName),
    typology: escapeHtml(options.typology || 'Sin especificar'),
    message: escapeHtml(options.message || 'Sin mensaje adicional').replace(/\n/g, '<br>'),
    reference: escapeHtml(options.reference),
    projectUrl: escapeHtml(options.projectUrl),
  };

  const html = `<!doctype html><html lang="es"><body style="margin:0;background:#f8fafc;font-family:Arial,sans-serif;color:#0f172a"><main style="max-width:620px;margin:32px auto;background:#fff;border:1px solid #e2e8f0;border-radius:20px;overflow:hidden"><header style="padding:30px 34px;background:${EMAIL_HEADER_COLOR};color:#fff"><p style="margin:0 0 8px;font-size:11px;letter-spacing:.18em;text-transform:uppercase;color:#cbd5e1">${safe.reference}</p><h1 style="margin:0;font-size:24px">${title}</h1></header><section style="padding:30px 34px;font-size:14px;line-height:1.65"><p style="margin:0 0 22px">Hola, <strong>${safe.fullName}</strong>. Recibimos tu solicitud sobre <strong>${safe.project}</strong>. El equipo responsable del master broker tiene una copia de este correo y dará seguimiento directamente.</p><table width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #e2e8f0;border-radius:14px;padding:14px 18px;background:#f8fafc"><tr><td style="padding:6px 0;color:#64748b;font-size:12px">Proyecto</td><td align="right" style="padding:6px 0;font-size:12px;font-weight:800">${safe.project}</td></tr><tr><td style="padding:6px 0;color:#64748b;font-size:12px">Solicitud</td><td align="right" style="padding:6px 0;font-size:12px;font-weight:800">${title}</td></tr><tr><td style="padding:6px 0;color:#64748b;font-size:12px">Perfil</td><td align="right" style="padding:6px 0;font-size:12px;font-weight:800">${safe.profile}</td></tr><tr><td style="padding:6px 0;color:#64748b;font-size:12px">Agencia</td><td align="right" style="padding:6px 0;font-size:12px;font-weight:800">${safe.agency}</td></tr><tr><td style="padding:6px 0;color:#64748b;font-size:12px">Teléfono</td><td align="right" style="padding:6px 0;font-size:12px;font-weight:800">${safe.phone}</td></tr><tr><td style="padding:6px 0;color:#64748b;font-size:12px">Correo</td><td align="right" style="padding:6px 0;font-size:12px;font-weight:800">${safe.email}</td></tr><tr><td style="padding:6px 0;color:#64748b;font-size:12px">Modelo</td><td align="right" style="padding:6px 0;font-size:12px;font-weight:800">${safe.typology}</td></tr></table><div style="margin:20px 0 0;padding:16px 18px;border-left:4px solid #7c3aed;background:#faf5ff"><p style="margin:0 0 6px;color:#64748b;font-size:11px;text-transform:uppercase;letter-spacing:.12em">Mensaje</p><p style="margin:0">${safe.message}</p></div><p style="margin:24px 0 0;text-align:center"><a href="${safe.projectUrl}" style="display:inline-block;background:${EMAIL_HEADER_COLOR};color:#fff;padding:12px 20px;border-radius:999px;text-decoration:none;font-weight:700">Ver proyecto</a></p><p style="margin:22px 0 0;color:#64748b;font-size:12px">Puedes responder este correo para continuar la conversación con el responsable comercial.</p></section><footer style="padding:20px 34px;background:#f8fafc;border-top:1px solid #e2e8f0;color:#94a3b8;font-size:11px;text-align:center">OB Brokers Team · Solicitud vinculada al proyecto ${safe.project}</footer></main></body></html>`;

  await mailer.sendMail({
    from: SMTP_CONFIG.from,
    to: customerEmail,
    ...(responsibleRecipients.length ? { cc: responsibleRecipients, replyTo: responsibleRecipients[0] } : {}),
    subject: `${title} · ${options.projectName} · ${options.reference}`,
    html,
  });
}

export async function sendSignedAgreementEmail({ recipients, agreementTitle, brokerName, expiresAt, pdf }: { recipients: string[]; agreementTitle: string; brokerName: string; expiresAt: Date; pdf: Uint8Array }) {
  const to = [...new Set(recipients.map((email) => email.trim().toLowerCase()).filter((email) => /^\S+@\S+\.\S+$/.test(email)))];
  if (!to.length) return;
  const safeTitle = escapeHtml(agreementTitle); const safeBroker = escapeHtml(brokerName); const expiry = escapeHtml(expiresAt.toLocaleDateString('es-DO', { day: 'numeric', month: 'long', year: 'numeric' }));
  await mailer.sendMail({ from: SMTP_CONFIG.from, to, subject: `Acuerdo firmado y sellado · ${agreementTitle}`, html: `<!doctype html><html lang="es"><body style="font-family:Arial,sans-serif;color:#0f172a"><main style="max-width:620px;margin:auto;border:1px solid #e2e8f0;border-radius:16px;overflow:hidden"><header style="background:${EMAIL_HEADER_COLOR};padding:28px;color:#fff"><h1 style="margin:0;font-size:22px">Acuerdo firmado y sellado</h1></header><section style="padding:28px"><p>El acuerdo <strong>${safeTitle}</strong> fue firmado por <strong>${safeBroker}</strong>.</p><p>Vigencia hasta: <strong>${expiry}</strong>.</p><p>Se adjunta el PDF final con evidencia de firma y sello. Consérvalo en el expediente comercial.</p></section></main></body></html>`, attachments: [{ filename: 'acuerdo-firmado.pdf', content: Buffer.from(pdf), contentType: 'application/pdf' }] });
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

export async function sendMagicLinkEmail({ to, name, magicUrl }: SendMagicLinkOptions) {
  const safeTo = escapeHtml(to);
  const safeName = escapeHtml(name);
  const safeMagicUrl = escapeHtml(magicUrl);
  const safeLogoUrl = escapeHtml(WHITE_LOGO_URL);

  const htmlContent = `
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Acceso al Portal · Osvaldo Bello Group</title>
  <style>
    body {
      margin: 0;
      padding: 0;
      background-color: #f8fafc;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      color: #0f172a;
      -webkit-font-smoothing: antialiased;
    }
    .wrapper {
      width: 100%;
      background-color: #f8fafc;
      padding: 40px 16px;
    }
    .container {
      max-width: 580px;
      margin: 0 auto;
      background-color: #ffffff;
      border-radius: 24px;
      overflow: hidden;
      border: 1px solid #e2e8f0;
      box-shadow: 0 10px 25px -5px rgba(15, 23, 42, 0.05);
    }
    .header {
      background-color: ${EMAIL_HEADER_COLOR};
      padding: 42px 40px;
      text-align: center;
    }
    .logo {
      display: block;
      width: 130px;
      max-width: 86%;
      height: auto;
      margin: 0 auto;
    }
    .content {
      padding: 40px;
    }
    .greeting {
      font-size: 18px;
      font-weight: 800;
      color: #0f172a;
      margin: 0 0 16px 0;
    }
    .text {
      font-size: 14px;
      line-height: 1.65;
      color: #475569;
      margin: 0 0 24px 0;
    }
    .badge-card {
      background-color: #f1f5f9;
      border: 1px solid #e2e8f0;
      border-radius: 16px;
      padding: 16px 20px;
      margin-bottom: 28px;
    }
    .badge-row {
      display: flex;
      justify-content: space-between;
      font-size: 12px;
      padding: 4px 0;
    }
    .badge-label {
      color: #64748b;
      font-weight: 600;
    }
    .badge-value {
      color: #0f172a;
      font-weight: 800;
    }
    .btn-container {
      text-align: center;
      margin: 32px 0;
    }
    .btn {
      display: inline-block;
      background-color: #0f172a;
      color: #ffffff !important;
      font-size: 14px;
      font-weight: 800;
      text-decoration: none;
      padding: 16px 36px;
      border-radius: 14px;
      letter-spacing: 0.02em;
      box-shadow: 0 4px 14px rgba(15, 23, 42, 0.2);
    }
    .notice {
      font-size: 12px;
      line-height: 1.5;
      color: #64748b;
      margin-top: 28px;
      border-top: 1px solid #f1f5f9;
      padding-top: 20px;
    }
    .fallback-link {
      display: inline-block;
      margin-top: 12px;
      color: #0C094E !important;
      font-size: 12px;
      font-weight: 800;
      text-decoration: none;
    }
    .footer {
      background-color: #f8fafc;
      padding: 24px 40px;
      text-align: center;
      border-top: 1px solid #e2e8f0;
    }
    .footer-text {
      font-size: 11px;
      color: #94a3b8;
      margin: 0;
      line-height: 1.5;
    }
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="container">
      <div class="header">
        <img src="${safeLogoUrl}" width="130" alt="Osvaldo Bello Group" class="logo">
      </div>
      
      <div class="content">
        <p class="greeting">Hola, ${safeName}:</p>
        <p class="text">
          Has recibido un enlace directo con permisos de <strong>Administrador</strong> para acceder al portal de gestión comercial, proyectos inmobiliarios e inventario en tiempo real de <strong>Osvaldo Bello Group</strong>.
        </p>

        <div class="badge-card">
          <table width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr>
              <td style="padding: 4px 0; color: #64748b; font-size: 12px; font-weight: 600;">Privilegios asignados:</td>
              <td align="right" style="padding: 4px 0; color: #0f172a; font-size: 12px; font-weight: 800;">Administrador Completo</td>
            </tr>
            <tr>
              <td style="padding: 4px 0; color: #64748b; font-size: 12px; font-weight: 600;">Método de acceso:</td>
              <td align="right" style="padding: 4px 0; color: #0f172a; font-size: 12px; font-weight: 800;">Magic Link (Sin contraseña)</td>
            </tr>
            <tr>
              <td style="padding: 4px 0; color: #64748b; font-size: 12px; font-weight: 600;">Vigencia del enlace:</td>
              <td align="right" style="padding: 4px 0; color: #2563eb; font-size: 12px; font-weight: 800;">30 minutos</td>
            </tr>
          </table>
        </div>

        <div class="btn-container">
          <a href="${safeMagicUrl}" class="btn" target="_blank">
            Acceder al Portal
          </a>
        </div>

        <p class="notice">
          Este enlace es confidencial, de un solo uso y expirará en 30 minutos.
          <br>
          <a href="${safeMagicUrl}" class="fallback-link" target="_blank">&#8599; Abrir enlace alternativo</a>
        </p>
      </div>

      <div class="footer">
        <p class="footer-text">
          &copy; 2026 Osvaldo Bello Group · Master Broker &amp; Real Estate Solutions.<br>
          Este correo fue enviado automáticamente a <strong>${safeTo}</strong>.
        </p>
      </div>
    </div>
  </div>
</body>
</html>
  `;

  return await mailer.sendMail({
    from: SMTP_CONFIG.from,
    to,
    subject: `Tu enlace de acceso al portal · Osvaldo Bello Group`,
    html: htmlContent,
  });
}

export async function sendInvitationEmail({
  to,
  inviteUrl,
  organizationName,
  roleLabel,
  invitedByName,
  expiresAt,
}: SendInvitationEmailOptions) {
  const safeTo = escapeHtml(to);
  const safeInviteUrl = escapeHtml(inviteUrl);
  const safeOrganizationName = escapeHtml(organizationName);
  const safeRoleLabel = escapeHtml(roleLabel);
  const safeInvitedByName = escapeHtml(invitedByName);
  const safeLogoUrl = escapeHtml(WHITE_LOGO_URL);
  const safeExpiration = escapeHtml(
    new Date(expiresAt).toLocaleDateString('es-DO', {
      day: 'numeric',
      month: 'long',
      year: 'numeric',
    })
  );

  const htmlContent = `
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Invitación al CRM · ${safeOrganizationName}</title>
  <style>
    body { margin: 0; padding: 0; background-color: #f8fafc; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #0f172a; }
    .wrapper { width: 100%; background-color: #f8fafc; padding: 40px 16px; }
    .container { max-width: 580px; margin: 0 auto; background-color: #ffffff; border: 1px solid #e2e8f0; border-radius: 22px; overflow: hidden; box-shadow: 0 12px 30px rgba(15, 23, 42, 0.07); }
    .header { padding: 42px 40px; background-color: ${EMAIL_HEADER_COLOR}; color: #ffffff; text-align: center; }
    .logo { display: block; width: 130px; max-width: 86%; height: auto; margin: 0 auto; }
    .title { margin: 30px 0 0; font-size: 23px; line-height: 1.25; font-weight: 900; }
    .content { padding: 36px 40px; }
    .text { margin: 0 0 22px; color: #475569; font-size: 14px; line-height: 1.65; }
    .details { margin: 0 0 28px; padding: 18px 20px; border: 1px solid #e2e8f0; border-radius: 16px; background-color: #f8fafc; }
    .row { padding: 5px 0; font-size: 12px; }
    .label { color: #64748b; font-weight: 700; }
    .value { color: #0f172a; font-weight: 900; text-align: right; }
    .btn-wrap { text-align: center; margin: 30px 0; }
    .btn { display: inline-block; padding: 15px 30px; border-radius: 14px; background-color: #0C094E; color: #ffffff !important; font-size: 14px; font-weight: 900; text-decoration: none; }
    .note { margin: 24px 0 0; padding-top: 18px; border-top: 1px solid #e2e8f0; color: #64748b; font-size: 12px; line-height: 1.55; }
    .fallback-link { display: inline-block; margin-top: 12px; color: #0C094E !important; font-size: 12px; font-weight: 800; text-decoration: none; }
    .footer { padding: 22px 40px; background-color: #f8fafc; border-top: 1px solid #e2e8f0; text-align: center; }
    .footer p { margin: 0; color: #94a3b8; font-size: 11px; line-height: 1.5; }
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="container">
      <div class="header">
        <img src="${safeLogoUrl}" width="130" alt="Osvaldo Bello Group" class="logo">
        <h1 class="title">Activa tu acceso al CRM de ${safeOrganizationName}</h1>
      </div>
      <div class="content">
        <p class="text">
          ${safeInvitedByName} te invitó a formar parte de <strong>${safeOrganizationName}</strong>.
          Para completar tu cuenta, abre el enlace y crea una contraseña segura.
        </p>
        <div class="details">
          <table width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr class="row">
              <td class="label">Correo invitado:</td>
              <td class="value">${safeTo}</td>
            </tr>
            <tr class="row">
              <td class="label">Rol asignado:</td>
              <td class="value">${safeRoleLabel}</td>
            </tr>
            <tr class="row">
              <td class="label">Vigencia:</td>
              <td class="value">Hasta ${safeExpiration}</td>
            </tr>
          </table>
        </div>
        <div class="btn-wrap">
          <a href="${safeInviteUrl}" class="btn" target="_blank">Crear contraseña y activar cuenta</a>
        </div>
        <p class="note">
          El enlace es personal y vence automáticamente.
          <br>
          <a href="${safeInviteUrl}" class="fallback-link" target="_blank">&#8599; Abrir enlace alternativo</a>
        </p>
      </div>
      <div class="footer">
        <p>Correo automático enviado a <strong>${safeTo}</strong>. Si no esperabas esta invitación, puedes ignorar este mensaje.</p>
      </div>
    </div>
  </div>
</body>
</html>
  `;

  return await mailer.sendMail({
    from: SMTP_CONFIG.from,
    to,
    subject: `Invitación para activar tu acceso al CRM · ${organizationName}`,
    html: htmlContent,
  });
}

export async function sendPasswordSetupEmail({
  to,
  setupUrl,
  organizationName,
  recipientName,
}: {
  to: string;
  setupUrl: string;
  organizationName: string;
  recipientName?: string;
}) {
  const safeTo = escapeHtml(to);
  const safeUrl = escapeHtml(setupUrl);
  const safeOrganization = escapeHtml(organizationName);
  const safeName = escapeHtml(recipientName || 'Hola');
  const html = `<!doctype html><html lang="es"><body style="margin:0;background:#f8fafc;font-family:Arial,sans-serif;color:#0f172a"><main style="max-width:580px;margin:32px auto;background:#fff;border:1px solid #e2e8f0;border-radius:18px;overflow:hidden"><header style="padding:32px;background:${EMAIL_HEADER_COLOR};color:#fff;text-align:center"><img src="${escapeHtml(WHITE_LOGO_URL)}" width="126" alt="OB Brokers Team" style="display:block;margin:0 auto 18px"><h1 style="margin:0;font-size:22px">Configura tu acceso al CRM</h1></header><section style="padding:32px;font-size:14px;line-height:1.65"><p>${safeName},</p><p>Se solicitó una nueva configuración de acceso para tu cuenta en <strong>${safeOrganization}</strong>. Por seguridad, elige tu propia contraseña usando el enlace siguiente.</p><p style="margin:28px 0;text-align:center"><a href="${safeUrl}" style="display:inline-block;background:#0C094E;color:#fff;text-decoration:none;border-radius:12px;padding:14px 24px;font-weight:800">Crear nueva contraseña</a></p><p style="color:#64748b;font-size:12px">El enlace es personal y temporal. Si no solicitaste este cambio, informa a tu administrador.</p><p><a href="${safeUrl}" style="color:#0C094E;font-size:12px;font-weight:700">Abrir enlace alternativo</a></p></section><footer style="padding:18px 32px;background:#f8fafc;border-top:1px solid #e2e8f0;color:#64748b;font-size:11px;text-align:center">Correo automático enviado a ${safeTo}.</footer></main></body></html>`;
  return mailer.sendMail({ from: SMTP_CONFIG.from, to, subject: `Configura tu acceso al CRM · ${organizationName}`, html });
}

export async function sendLeadReportEmails(options: SendLeadReportEmailOptions) {
  const clientName = escapeHtml(options.clientName);
  const projectName = escapeHtml(options.projectName);
  const developerName = escapeHtml(options.developerName);
  const agencyName = escapeHtml(options.agencyName);
  const agentName = escapeHtml(options.agentName);
  const workSummary = escapeHtml(options.workSummary).replace(/\n/g, '<br>');
  const reviewUrl = escapeHtml(options.reviewUrl);
  const recipients = [...new Set(options.reviewers.map((email) => email.trim().toLowerCase()).filter((email) => /^\S+@\S+\.\S+$/.test(email)))];
  const card = `<div style="border:1px solid #e2e8f0;border-radius:14px;padding:16px;margin:18px 0;background:#f8fafc"><p style="margin:0 0 8px;font-size:12px;color:#64748b">Desarrolladora / proyecto</p><p style="margin:0;font-weight:800">${developerName} · ${projectName}</p><p style="margin:16px 0 8px;font-size:12px;color:#64748b">Gestión declarada</p><p style="margin:0;line-height:1.6">${workSummary}</p></div>`;
  const base = (body: string) => `<!doctype html><html lang="es"><body style="margin:0;background:#f8fafc;font-family:Arial,sans-serif;color:#0f172a"><main style="max-width:620px;margin:32px auto;background:#fff;border:1px solid #e2e8f0;border-radius:18px;overflow:hidden"><header style="padding:28px 32px;background:${EMAIL_HEADER_COLOR};color:#fff"><img src="${escapeHtml(WHITE_LOGO_URL)}" width="126" alt="OB Brokers Team" style="display:block;margin-bottom:20px"><h1 style="margin:0;font-size:23px">Reporte de cliente</h1></header><section style="padding:28px 32px;font-size:14px;line-height:1.6">${body}</section></main></body></html>`;
  const tasks: Promise<unknown>[] = [];
  if (options.clientEmail && /^\S+@\S+\.\S+$/.test(options.clientEmail)) tasks.push(mailer.sendMail({ from: SMTP_CONFIG.from, to: options.clientEmail, subject: `Reporte en proceso · ${projectName}`, html: base(`<p>Hola, <strong>${clientName}</strong>.</p><p>Tu información fue reportada para ${developerName} / ${projectName}. El equipo validará el reporte y recibirás una notificación cuando exista una decisión.</p>${card}<p style="color:#64748b;font-size:12px">Este mensaje no confirma una reserva ni modifica condiciones comerciales.</p>`) }));
  if (recipients.length) tasks.push(mailer.sendMail({ from: SMTP_CONFIG.from, to: recipients, subject: `Solicitud de reporte · ${clientName} · ${projectName}`, html: base(`<p><strong>${agentName}</strong>, de <strong>${agencyName}</strong>, acaba de solicitar el siguiente reporte de cliente.</p><p><strong>Cliente:</strong> ${clientName}</p>${card}<p><a href="${reviewUrl}" style="display:inline-block;background:#0C094E;color:#fff;padding:12px 18px;border-radius:9px;text-decoration:none;font-weight:700">Revisar en el CRM</a></p>`) }));
  await Promise.allSettled(tasks);
}

export async function sendAgencyOnboardingReviewEmail({
  to,
  agencyName,
  legalName,
  taxId,
  legalAddress,
  contactEmail,
  contactPhone,
  representativeName,
  representativePhone,
  representativeEmail,
  reviewUrl,
}: SendAgencyOnboardingReviewEmailOptions) {
  const recipient =
    to ||
    process.env.AGENCY_REVIEW_EMAIL ||
    process.env.ADMIN_NOTIFICATION_EMAIL ||
    process.env.SMTP_USER;

  if (!recipient) {
    throw new Error('No hay correo configurado para revisar solicitudes de agencia.');
  }

  const safeLogoUrl = escapeHtml(WHITE_LOGO_URL);
  const rows = [
    ['Agencia', agencyName],
    ['Razón social', legalName || agencyName],
    ['RNC / Identificación fiscal', taxId || 'No indicado'],
    ['Dirección legal', legalAddress || 'No indicada'],
    ['Correo de agencia', contactEmail],
    ['Teléfono de agencia', contactPhone || 'No indicado'],
    ['Representante', representativeName],
    ['Correo representante', representativeEmail],
    ['Teléfono representante', representativePhone || 'No indicado'],
  ];

  const details = rows
    .map(
      ([label, value]) => `
        <tr>
          <td style="padding: 8px 0; color: #64748b; font-size: 12px; font-weight: 700;">${escapeHtml(label)}</td>
          <td align="right" style="padding: 8px 0; color: #0f172a; font-size: 12px; font-weight: 900;">${escapeHtml(value)}</td>
        </tr>
      `
    )
    .join('');

  const htmlContent = `
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Nueva agencia pendiente de revisión</title>
</head>
<body style="margin:0; padding:0; background:#f8fafc; font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif; color:#0f172a;">
  <div style="width:100%; background:#f8fafc; padding:40px 16px;">
    <div style="max-width:620px; margin:0 auto; background:#fff; border:1px solid #e2e8f0; border-radius:22px; overflow:hidden;">
      <div style="background:${EMAIL_HEADER_COLOR}; padding:34px 40px; text-align:center;">
        <img src="${safeLogoUrl}" width="128" alt="Osvaldo Bello Group" style="display:block; width:128px; max-width:86%; height:auto; margin:0 auto;">
      </div>
      <div style="padding:34px 40px;">
        <p style="margin:0 0 8px; color:#0C094E; font-size:11px; font-weight:900; letter-spacing:.14em; text-transform:uppercase;">Revisión requerida</p>
        <h1 style="margin:0 0 16px; font-size:24px; line-height:1.22; font-weight:900;">Nueva agencia completó sus datos</h1>
        <p style="margin:0 0 24px; color:#475569; font-size:14px; line-height:1.65;">
          Revisa la información antes de crear o habilitar el acceso. Así puedes confirmar que el perfil público y comercial se vea correcto.
        </p>
        <table width="100%" cellpadding="0" cellspacing="0" border="0" style="border:1px solid #e2e8f0; border-radius:16px; padding:12px 18px; background:#f8fafc;">
          ${details}
        </table>
        <div style="text-align:center; margin:30px 0 0;">
          <a href="${escapeHtml(reviewUrl)}" target="_blank" style="display:inline-block; background:#0C094E; color:#fff; text-decoration:none; border-radius:14px; padding:14px 28px; font-size:13px; font-weight:900;">
            Revisar en el CRM
          </a>
        </div>
      </div>
    </div>
  </div>
</body>
</html>
  `;

  return await mailer.sendMail({
    from: SMTP_CONFIG.from,
    to: recipient,
    subject: `Nueva agencia pendiente de revisión · ${agencyName}`,
    html: htmlContent,
  });
}

export async function sendBrokerAccessReviewEmail(options: SendBrokerAccessReviewEmailOptions) {
  const recipient = options.to || process.env.AGENCY_REVIEW_EMAIL || process.env.ADMIN_NOTIFICATION_EMAIL || 'soporte@osvaldobello.com';
  if (!recipient) throw new Error('No hay correo configurado para revisar solicitudes de brokers.');
  const rows = [
    ['Nombre', options.fullName],
    ['Correo', options.email],
    ['Teléfono', options.phone],
    ['Perfil', options.roleType],
    ['Agencia', options.agency || 'Independiente'],
    ['Proyecto de interés', options.projectInterest || 'No indicado'],
  ].map(([label, value]) => `<tr><td style="padding:8px 0;color:#64748b;font-size:12px;font-weight:700">${escapeHtml(label)}</td><td align="right" style="padding:8px 0;color:#0f172a;font-size:12px;font-weight:900">${escapeHtml(value)}</td></tr>`).join('');
  const note = options.message ? `<p style="margin:20px 0 0;color:#475569;font-size:13px;line-height:1.6"><strong>Mensaje:</strong><br>${escapeHtml(options.message).replace(/\n/g, '<br>')}</p>` : '';
  const html = `<!doctype html><html lang="es"><body style="margin:0;background:#f8fafc;font-family:Arial,sans-serif;color:#0f172a"><main style="max-width:620px;margin:32px auto;background:#fff;border:1px solid #e2e8f0;border-radius:18px;overflow:hidden"><header style="padding:28px 32px;background:${EMAIL_HEADER_COLOR};color:#fff"><h1 style="margin:0;font-size:23px">Nueva solicitud de acceso profesional</h1></header><section style="padding:28px 32px;font-size:14px;line-height:1.6"><p style="margin:0 0 18px">Un broker solicitó acceso a la red comercial. Revísalo antes de crear cualquier cuenta o membresía.</p><table width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #e2e8f0;border-radius:14px;padding:12px 18px;background:#f8fafc">${rows}</table>${note}<p style="margin:24px 0 0"><a href="${escapeHtml(options.reviewUrl)}" style="display:inline-block;background:${EMAIL_HEADER_COLOR};color:#fff;padding:12px 18px;border-radius:9px;text-decoration:none;font-weight:700">Revisar solicitud</a></p></section></main></body></html>`;
  await mailer.sendMail({ from: SMTP_CONFIG.from, to: recipient, subject: `Solicitud de broker · ${options.fullName}`, html });
}

export interface SendProposalEmailOptions {
  to: string;
  replyTo?: string;
  recipientName: string;
  projectName: string;
  unitSummary: string;
  brokerName: string;
  brokerPhone?: string;
  agencyName?: string;
  agencyLogo?: string;
  proposalUrl: string;
  expiresAt: string;
}

export async function sendProposalEmail({
  to,
  replyTo,
  recipientName,
  projectName,
  unitSummary,
  brokerName,
  brokerPhone,
  agencyName,
  agencyLogo,
  proposalUrl,
  expiresAt,
}: SendProposalEmailOptions) {
  const safeTo = escapeHtml(to);
  const validReplyTo = replyTo && /^\S+@\S+\.\S+$/.test(replyTo.trim()) ? replyTo.trim() : undefined;
  const safeName = escapeHtml(recipientName);
  const safeProject = escapeHtml(projectName);
  const safeUnit = escapeHtml(unitSummary);
  const safeBroker = escapeHtml(brokerName);
  const safeAgency = escapeHtml(agencyName || 'Osvaldo Bello Group');
  const safeUrl = escapeHtml(proposalUrl);
  const safeLogoUrl = agencyLogo ? escapeHtml(agencyLogo) : escapeHtml(WHITE_LOGO_URL);
  const safePhone = brokerPhone ? escapeHtml(brokerPhone) : '';
  const safeExpiry = escapeHtml(
    new Date(expiresAt).toLocaleDateString('es-DO', {
      day: 'numeric',
      month: 'long',
      year: 'numeric',
    })
  );

  const htmlContent = `
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Propuesta comercial · ${safeProject}</title>
  <style>
    body { margin: 0; padding: 0; background-color: #f8fafc; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #0f172a; }
    .wrapper { width: 100%; background-color: #f8fafc; padding: 40px 16px; }
    .container { max-width: 580px; margin: 0 auto; background-color: #ffffff; border: 1px solid #e2e8f0; border-radius: 22px; overflow: hidden; box-shadow: 0 12px 30px rgba(15, 23, 42, 0.07); }
    .header { padding: 42px 40px; background-color: ${EMAIL_HEADER_COLOR}; color: #ffffff; text-align: center; }
    .logo { display: block; width: 130px; max-width: 86%; height: auto; margin: 0 auto; }
    .title { margin: 24px 0 0; font-size: 22px; line-height: 1.25; font-weight: 900; }
    .content { padding: 36px 40px; }
    .text { margin: 0 0 22px; color: #475569; font-size: 14px; line-height: 1.65; }
    .details { margin: 0 0 28px; padding: 18px 20px; border: 1px solid #e2e8f0; border-radius: 16px; background-color: #f8fafc; }
    .row td { padding: 6px 0; font-size: 12px; }
    .label { color: #64748b; font-weight: 700; }
    .value { color: #0f172a; font-weight: 900; text-align: right; }
    .btn-wrap { text-align: center; margin: 30px 0; }
    .btn { display: inline-block; padding: 15px 30px; border-radius: 14px; background-color: #0C094E; color: #ffffff !important; font-size: 14px; font-weight: 900; text-decoration: none; }
    .note { margin: 24px 0 0; padding-top: 18px; border-top: 1px solid #e2e8f0; color: #64748b; font-size: 12px; line-height: 1.55; }
    .fallback-link { display: inline-block; margin-top: 12px; color: #0C094E !important; font-size: 12px; font-weight: 800; text-decoration: none; }
    .footer { padding: 22px 40px; background-color: #f8fafc; border-top: 1px solid #e2e8f0; text-align: center; }
    .footer p { margin: 0; color: #94a3b8; font-size: 11px; line-height: 1.5; }
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="container">
      <div class="header">
        <img src="${safeLogoUrl}" width="130" alt="${safeAgency}" class="logo">
        <h1 class="title">Propuesta comercial</h1>
      </div>
      <div class="content">
        <p class="text">
          Hola, <strong>${safeName}</strong>. Tu asesor <strong>${safeBroker}</strong> ha preparado una propuesta comercial para ti.
        </p>
        <div class="details">
          <table width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr class="row">
              <td class="label">Proyecto</td>
              <td class="value">${safeProject}</td>
            </tr>
            <tr class="row">
              <td class="label">Unidad(es)</td>
              <td class="value">${safeUnit}</td>
            </tr>
            <tr class="row">
              <td class="label">Asesor</td>
              <td class="value">${safeBroker}</td>
            </tr>${safePhone ? `
            <tr class="row">
              <td class="label">Contacto</td>
              <td class="value">${safePhone}</td>
            </tr>` : ''}
            <tr class="row">
              <td class="label">Vigencia</td>
              <td class="value" style="color: #2563eb;">Hasta ${safeExpiry}</td>
            </tr>
          </table>
        </div>
        <div class="btn-wrap">
          <a href="${safeUrl}" class="btn" target="_blank">Ver propuesta completa</a>
        </div>
        <p class="note">
          Este enlace es confidencial y expirará automáticamente. Los precios y disponibilidad están sujetos a confirmación al momento de la reserva.
          <br>
          <a href="${safeUrl}" class="fallback-link" target="_blank">&#8599; Abrir enlace alternativo</a>
        </p>
      </div>
      <div class="footer">
        <p>
          &copy; 2026 ${safeAgency} &middot; Propuesta enviada automáticamente a <strong>${safeTo}</strong>.
        </p>
      </div>
    </div>
  </div>
</body>
</html>
  `;

  return await mailer.sendMail({
    from: SMTP_CONFIG.from,
    to,
    ...(validReplyTo ? { replyTo: validReplyTo } : {}),
    subject: `Propuesta comercial · ${projectName}`,
    html: htmlContent,
  });
}

export async function sendAccessRequestReceivedEmail({
  to,
  fullName,
  roleType,
  agency,
}: SendAccessRequestReceivedEmailOptions) {
  const safeTo = escapeHtml(to);
  const safeFullName = escapeHtml(fullName);
  const safeRoleType = escapeHtml(roleType);
  const safeAgency = escapeHtml(agency || 'Independiente');
  const safeLogoUrl = escapeHtml(WHITE_LOGO_URL);

  const htmlContent = `
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Solicitud recibida · OB Brokers Team</title>
</head>
<body style="margin:0; padding:0; background:#f8fafc; font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif; color:#0f172a;">
  <div style="width:100%; background:#f8fafc; padding:40px 16px;">
    <div style="max-width:580px; margin:0 auto; background:#fff; border:1px solid #e2e8f0; border-radius:22px; overflow:hidden;">
      <div style="background:${EMAIL_HEADER_COLOR}; padding:36px 40px; text-align:center;">
        <img src="${safeLogoUrl}" width="128" alt="Osvaldo Bello Group" style="display:block; width:128px; max-width:86%; height:auto; margin:0 auto;">
      </div>
      <div style="padding:36px 40px;">
        <h1 style="margin:0 0 14px; font-size:23px; line-height:1.24; font-weight:900;">Recibimos tu solicitud</h1>
        <p style="margin:0 0 22px; color:#475569; font-size:14px; line-height:1.65;">
          Hola, <strong>${safeFullName}</strong>. Nuestro equipo revisará tu información antes de habilitar cualquier acceso al CRM.
        </p>
        <table width="100%" cellpadding="0" cellspacing="0" border="0" style="border:1px solid #e2e8f0; border-radius:16px; padding:12px 18px; background:#f8fafc;">
          <tr>
            <td style="padding:8px 0; color:#64748b; font-size:12px; font-weight:700;">Perfil solicitado</td>
            <td align="right" style="padding:8px 0; color:#0f172a; font-size:12px; font-weight:900;">${safeRoleType}</td>
          </tr>
          <tr>
            <td style="padding:8px 0; color:#64748b; font-size:12px; font-weight:700;">Agencia</td>
            <td align="right" style="padding:8px 0; color:#0f172a; font-size:12px; font-weight:900;">${safeAgency}</td>
          </tr>
        </table>
        <p style="margin:22px 0 0; color:#64748b; font-size:12px; line-height:1.6;">
          Si tu perfil es aprobado, recibirás un nuevo correo con los próximos pasos. Este mensaje no activa acceso ni contraseña.
        </p>
      </div>
      <div style="padding:22px 40px; background:#f8fafc; border-top:1px solid #e2e8f0; text-align:center;">
        <p style="margin:0; color:#94a3b8; font-size:11px; line-height:1.5;">Correo automático enviado a <strong>${safeTo}</strong>.</p>
      </div>
    </div>
  </div>
</body>
</html>
  `;

  return await mailer.sendMail({
    from: SMTP_CONFIG.from,
    to,
    subject: 'Solicitud recibida · OB Brokers Team',
    html: htmlContent,
  });
}
