'use client';
import { useState } from 'react';
import { useWorkflow } from '@/lib/demo/use-workflow';
import { commissionAmount, documentNumber, fiscalNumber, FICTIONAL_AGENCY } from '@/lib/demo/browser-workflow';
import { downloadCommissionDocument } from '@/lib/demo/commission-pdf';
import { formatCurrency } from '@/lib/utils';

export default function DemoCommissionDocument({ code, kind }: { code: string; kind: 'proforma' | 'factura' }) {
  const { state, ready } = useWorkflow(); const [error, setError] = useState(''); const deal = state.deals.find(item => item.id === code);
  if (!ready) return <p className="p-6">Cargando documento…</p>;
  if (!deal || !(kind === 'proforma' ? deal.proformaAt : deal.invoiceAt)) return <p className="p-6">Documento no encontrado.</p>;
  return <div className="mx-auto max-w-4xl pb-10"><div className="mb-5 flex gap-3 print:hidden"><button onClick={() => window.print()} className="rounded-xl border border-slate-300 bg-white px-5 py-3 text-sm font-semibold">Imprimir</button><button onClick={() => { void downloadCommissionDocument(deal, kind).catch(cause => setError(cause.message)); }} className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white">Descargar PDF</button></div>{error && <p role="alert">{error}</p>}
    <article className="commission-sheet overflow-hidden border border-slate-200 bg-white text-slate-950"><header className="flex flex-wrap justify-between gap-6 bg-slate-950 p-8 text-white sm:p-12"><div><p className="text-3xl font-bold tracking-tight">HORIZONTE</p><p className="mt-1 text-xs tracking-widest">ASESORES INMOBILIARIOS</p><h1 className="mt-6 text-xl font-bold">{kind === 'proforma' ? 'Proforma de comisión' : 'Factura de comisión'}</h1></div><div><p className="font-bold">{documentNumber(deal, kind)}</p><p className="mt-2 text-sm">{new Date(kind === 'proforma' ? deal.proformaAt! : deal.invoiceAt!).toLocaleDateString('es-DO')}</p></div></header>
    <div className="p-8 sm:p-12"><div className="flex flex-wrap justify-between gap-6"><div><p className="font-semibold">{FICTIONAL_AGENCY.name}</p><p className="mt-2 text-sm text-slate-600">RNC: {FICTIONAL_AGENCY.taxId}</p><p className="text-sm text-slate-600">{FICTIONAL_AGENCY.address}</p><p className="text-sm text-slate-600">{FICTIONAL_AGENCY.email}</p></div>{kind === 'factura' && <div><p className="text-sm text-slate-600">Comprobante fiscal</p><p className="mt-1 text-lg font-bold tabular-nums">{fiscalNumber(deal)}</p></div>}</div>
      <div className="my-8 border-y border-slate-200 py-6"><p className="text-sm text-slate-600">Facturar a</p><p className="mt-2 text-xl font-semibold">{deal.developer}</p><p className="mt-2 text-sm">Proyecto: {deal.projectName} · Unidad: {deal.unitCode}</p><p className="mt-1 text-sm">Cliente: {deal.clientName}</p></div>
      <div className="flex justify-between gap-5 bg-slate-100 px-4 py-3 text-xs font-bold"><span>DESCRIPCIÓN</span><span>IMPORTE</span></div><div className="flex flex-wrap justify-between gap-4 border-b border-slate-200 px-4 py-6"><div><p className="font-semibold">Servicios de intermediación inmobiliaria</p><p className="mt-2 text-sm text-slate-600">Comisión del {deal.commissionRate}% sobre {formatCurrency(deal.price, deal.currency)}</p></div><strong>{formatCurrency(commissionAmount(deal), deal.currency)}</strong></div>
      <div className="ml-auto mt-7 max-w-xs"><p className="flex justify-between gap-3 text-sm"><span>Comisión liberada</span><span>{formatCurrency(commissionAmount(deal), deal.currency)}</span></p><p className="mt-5 flex justify-between gap-3 border-t border-slate-200 pt-5 text-xl font-bold"><span>Total</span><span>{formatCurrency(commissionAmount(deal), deal.currency)}</span></p></div>
      <div className="mt-8 flex h-32 w-32 rotate-[-10deg] flex-col items-center justify-center rounded-full border-[3px] border-emerald-800 text-center text-emerald-800"><p className="text-sm font-bold">HORIZONTE</p><p className="my-2 text-[10px] font-bold">ADMINISTRACIÓN</p><p className="text-[10px] font-bold">AUTORIZADO</p></div><p className="mt-5 text-sm font-semibold">Departamento de administración</p><footer className="mt-8 flex justify-between gap-4 border-t border-slate-200 pt-4 text-xs text-slate-600"><span>{deal.projectName} · {deal.unitCode}</span><span>Página 1 de 1</span></footer>
    </div></article><style>{`@media print { body * { visibility: hidden; } .commission-sheet, .commission-sheet * { visibility: visible; } .commission-sheet { position: absolute; left: 0; top: 0; width: 100%; border: 0; print-color-adjust: exact; } }`}</style>
  </div>;
}
