'use client';
import { UITranslationBoundary, LocalizedText } from '@/components/i18n/UITranslationBoundary';


import { useState } from 'react';
import { BarChart3, Building2, CalendarDays, FileText, Handshake, Users } from 'lucide-react';
import type { ReportingOverview } from '@/lib/data/project-reporting';

type Tab = 'resumen' | 'clientes' | 'negociaciones' | 'propuestas' | 'unidades';
const tabs: Array<{ id: Tab; label: string }> = [
  { id: 'resumen', label: 'Resumen' }, { id: 'clientes', label: 'Clientes reportados' },
  { id: 'negociaciones', label: 'Negociaciones' }, { id: 'propuestas', label: 'Propuestas' }, { id: 'unidades', label: 'Unidades' },
];
const stageLabels: Record<string, string> = { new: 'Nuevo', contacted: 'Contactado', qualified: 'Calificado', proposal: 'Propuesta', negotiation: 'Negociación', reservation: 'Reserva', won: 'Cerrada', lost: 'Perdida', paused: 'Pausada' };
const commissionLabels: Record<string, string> = { payment_pending: 'Pendiente de pago', eligible: 'Elegible', proforma_submitted: 'Proforma enviada', under_review: 'En revisión', correction_requested: 'Corrección solicitada', approved: 'Aprobada', invoice_pending: 'Factura pendiente', invoice_submitted: 'Factura enviada', processing_payment: 'Pago en proceso', paid: 'Pagada', rejected: 'Rechazada', cancelled: 'Cancelada' };
function date(value: string | null) { return value ? new Intl.DateTimeFormat('es-DO', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value)) : '—'; }
function money(value: number, currency: string) { return new Intl.NumberFormat('es-DO', { style: 'currency', currency, maximumFractionDigits: 0 }).format(value); }
function Empty({ label }: { label: string }) { return <p className="rounded-xl border border-dashed border-slate-200 bg-slate-50 px-5 py-12 text-center text-sm text-slate-500">{label}</p>; }
function Metric({ icon: Icon, label, value, note }: { icon: typeof Users; label: string; value: string | number; note?: string }) {
  return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-slate-500">{label}</span><Icon className="h-4 w-4 text-slate-400" /></div><p className="mt-3 text-2xl font-extrabold text-slate-950">{value}</p>{note && <p className="mt-1 text-xs text-slate-500">{note}</p>}</div>;
}
function Table({ heads, children }: { heads: string[]; children: React.ReactNode }) {
  return <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[840px] text-left text-xs"><thead className="bg-slate-50 text-[10px] font-extrabold uppercase tracking-wide text-slate-500"><tr>{heads.map((head) => <th key={head} className="whitespace-nowrap border-b border-slate-200 px-4 py-3">{head}</th>)}</tr></thead><tbody className="divide-y divide-slate-100 text-slate-700">{children}</tbody></table></div>;
}

export default function ProjectReportingDashboard({ overview, description }: { overview: ReportingOverview; description: string }) {
  const [tab, setTab] = useState<Tab>('resumen');
  const [projectId, setProjectId] = useState<number | 'all'>('all');
  const selectedProject = overview.projects.find((project) => project.id === projectId);
  const matches = (name: string) => !selectedProject || name.split(', ').includes(selectedProject.name);
  const leads = overview.leads.filter((row) => matches(row.project));
  const negotiations = overview.negotiations.filter((row) => matches(row.project));
  const proposals = overview.proposals.filter((row) => matches(row.project));
  const units = overview.units.filter((row) => matches(row.project));
  const projectCount = selectedProject ? 1 : overview.projects.length;
  const stages = Object.entries(negotiations.reduce<Record<string, number>>((counts, row) => { counts[row.stage] = (counts[row.stage] ?? 0) + 1; return counts; }, {}));
  const commissions = Object.entries(selectedProject ? overview.commissionCountsByProject[selectedProject.id] ?? {} : overview.commissionCounts);
  const activeAgencies = new Set([...leads.map((row) => row.agency), ...negotiations.map((row) => row.agency), ...proposals.map((row) => row.agency)].filter((value) => value !== '—')).size;
  const lastLeadAt = leads[0]?.reportedAt ?? null;
  const salesCount = selectedProject ? overview.salesByProject[selectedProject.id]?.count ?? 0 : overview.salesCount;
  const salesVolume = selectedProject ? overview.salesByProject[selectedProject.id]?.volumeByCurrency ?? {} : overview.salesVolumeByCurrency;

  return <div className="portal-enter space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.18em] text-blue-700"><LocalizedText text={"Seguimiento de proyectos · Solo lectura"} /></p><h1 className="mt-1 text-2xl font-extrabold text-slate-950">{overview.scopeName}</h1><p className="mt-1 max-w-2xl text-sm text-slate-500">{description}</p></div>
      {overview.projects.length > 1 && <label className="text-xs font-bold text-slate-600"><LocalizedText text={"Proyecto"} /><UITranslationBoundary attributes={["aria-label"]}><select aria-label="Filtrar por proyecto" value={projectId} onChange={(event) => setProjectId(event.target.value === 'all' ? 'all' : Number(event.target.value))} className="mt-1 block min-w-56 rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-900 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-100"><option value="all"><LocalizedText text={"Todos los proyectos"} /></option>{overview.projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></UITranslationBoundary></label>}
    </div>
    {overview.limited && <p role="status" className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs text-amber-900"><LocalizedText text={"Hay más registros de los que caben en esta vista. Los totales mostrados pueden ser parciales; solicita un reporte completo."} /></p>}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><UITranslationBoundary attributes={["label"]}><Metric icon={Building2} label="Proyectos" value={projectCount} /></UITranslationBoundary><UITranslationBoundary attributes={["label"]}><Metric icon={Users} label="Clientes reportados" value={leads.length} note={`Último reporte: ${date(lastLeadAt)}`} /></UITranslationBoundary><UITranslationBoundary attributes={["label"]}><Metric icon={Handshake} label="Negociaciones" value={negotiations.length} /></UITranslationBoundary><UITranslationBoundary attributes={["label"]}><Metric icon={FileText} label="Propuestas" value={proposals.length} /></UITranslationBoundary></div>
    <UITranslationBoundary attributes={["aria-label"]}><div className="flex gap-1 overflow-x-auto rounded-xl border border-slate-200 bg-white p-1" role="tablist" aria-label="Datos de proyectos">{tabs.map((item) => <button key={item.id} type="button" role="tab" aria-selected={tab === item.id} onClick={() => setTab(item.id)} className={`whitespace-nowrap rounded-lg px-4 py-2.5 text-xs font-bold transition ${tab === item.id ? 'bg-slate-950 text-white shadow-sm' : 'text-slate-600 hover:bg-slate-50'}`}>{item.label}</button>)}</div></UITranslationBoundary>
    {tab === 'resumen' && <div className="space-y-5">
      <div className="grid gap-3 sm:grid-cols-3"><UITranslationBoundary attributes={["label"]}><Metric icon={Users} label="Agencias con actividad" value={activeAgencies} /></UITranslationBoundary><UITranslationBoundary attributes={["label"]}><Metric icon={CalendarDays} label="Cierres registrados" value={salesCount} /></UITranslationBoundary><UITranslationBoundary attributes={["label"]}><Metric icon={BarChart3} label="Unidades disponibles" value={units.filter((unit) => unit.status === 'available').length} /></UITranslationBoundary></div>
      <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-extrabold text-slate-900"><LocalizedText text={"Etapas de negociación"} /></h2>{stages.length ? <div className="mt-4 space-y-4">{stages.map(([stage, count]) => <div key={stage} className="space-y-1.5 text-sm"><div className="flex items-center justify-between"><span className="text-slate-600">{stageLabels[stage] ?? stage}</span><span className="font-extrabold text-slate-900">{count}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{ width: `${Math.max(8, (count / negotiations.length) * 100)}%` }} /></div></div>)}</div> : <p className="mt-5 text-sm text-slate-500"><LocalizedText text={"Todavía no hay negociaciones."} /></p>}</section><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-extrabold text-slate-900"><LocalizedText text={"Comisiones por estado"} /></h2>{commissions.length ? <div className="mt-4 space-y-3">{commissions.map(([status, count]) => <div key={status} className="flex items-center justify-between border-b border-slate-100 pb-2 text-sm"><span className="text-slate-600">{commissionLabels[status] ?? status}</span><span className="font-extrabold text-slate-900">{count}</span></div>)}</div> : <p className="mt-5 text-sm text-slate-500"><LocalizedText text={"Todavía no hay comisiones registradas."} /></p>}</section></div>
      {Object.keys(salesVolume).length > 0 && <p className="rounded-xl border border-blue-100 bg-blue-50 px-4 py-3 text-sm text-slate-700"><LocalizedText text={"Volumen de ventas registradas: "} />{Object.entries(salesVolume).map(([currency, amount]) => money(amount, currency)).join(' · ')}</p>}
    </div>}
    {tab === 'clientes' && (leads.length ? <><p className="text-xs text-slate-500"><LocalizedText text={"El vencimiento se muestra según la protección registrada; los reportes pendientes aún no tienen fecha de vencimiento."} /></p><Table heads={['Cliente', 'Teléfono', 'Correo', 'Proyecto', 'Agencia', 'Agente', 'Reportado', 'Vence', 'Estado']}>{leads.map((row) => <tr key={row.id}>{[row.client, row.phone, row.email, row.project, row.agency, row.agent, date(row.reportedAt), row.expiresAt ? date(row.expiresAt) : 'Pendiente', row.status].map((value, index) => <td key={index} className="max-w-48 truncate px-4 py-3" title={value}>{value}</td>)}</tr>)}</Table></> : <UITranslationBoundary attributes={["label"]}><Empty label="No hay clientes reportados para este proyecto." /></UITranslationBoundary>)}
    {tab === 'negociaciones' && (negotiations.length ? <><p className="text-xs text-slate-500"><LocalizedText text={"Vista de seguimiento: muestra responsables, unidades y etapas sin abrir el expediente privado de la negociación."} /></p><Table heads={['Proyecto', 'Agencia', 'Agente', 'Unidad', 'Etapa', 'Última actividad']}>{negotiations.map((row) => <tr key={row.id}>{[row.project, row.agency, row.agent, row.unit, stageLabels[row.stage] ?? row.stage, date(row.updatedAt)].map((value, index) => <td key={index} className="px-4 py-3">{value}</td>)}</tr>)}</Table></> : <UITranslationBoundary attributes={["label"]}><Empty label="No hay negociaciones registradas para este proyecto." /></UITranslationBoundary>)}
    {tab === 'propuestas' && (proposals.length ? <><p className="text-xs text-slate-500"><LocalizedText text={"Se muestra quién hizo la propuesta, el cliente y las unidades. El documento y los datos privados de la propuesta no se abren aquí."} /></p><Table heads={['Proyecto', 'Agencia', 'Autor', 'Cliente', 'Unidades', 'Estado', 'Creada']}>{proposals.map((row) => <tr key={row.id}>{[row.project, row.agency, row.author, row.client, row.units, row.status, date(row.createdAt)].map((value, index) => <td key={index} className="px-4 py-3">{value}</td>)}</tr>)}</Table></> : <UITranslationBoundary attributes={["label"]}><Empty label="No hay propuestas publicadas para este proyecto." /></UITranslationBoundary>)}
    {tab === 'unidades' && (units.length ? <Table heads={['Proyecto', 'Unidad', 'Estado', 'Precio']}>{units.map((row) => <tr key={row.id}>{[row.project, row.code, row.status, money(row.price, row.currency)].map((value, index) => <td key={index} className="px-4 py-3">{value}</td>)}</tr>)}</Table> : <UITranslationBoundary attributes={["label"]}><Empty label="No hay unidades registradas para este proyecto." /></UITranslationBoundary>)}
  </div>;
}
