'use client';
import { UITranslationBoundary, LocalizedText } from '@/components/i18n/UITranslationBoundary';


import { useMemo, useState } from 'react';
import Link from 'next/link';
import { Check, ChevronRight, Search } from 'lucide-react';
import type { PortalProject, PortalProjectTypology, PortalUnit } from '@/lib/portal-projects';
import { formatCurrency } from '@/lib/utils';

const money = (value: string | undefined) => Number((value || '').replace(/[^\d.,-]/g, '').replace(/,/g, '')) || 0;

function typologyPrice(unit: PortalUnit, typology: PortalProjectTypology) {
  const keys = [typology.key, typology.id, typology.name].filter(Boolean) as string[];
  return keys.map((key) => money(unit.customColumns?.[key])).find((price) => price > 0) || typology.startingPrice || unit.price;
}

function unitSummary({ bedrooms, bathrooms, parkingSpaces, area }: { bedrooms?: number; bathrooms?: number; parkingSpaces?: number; area?: number }) {
  const parkings = Number(parkingSpaces || 0);
  return [
    `${bedrooms || 0} hab.`,
    `${bathrooms || 0} baños`,
    parkings > 0 ? `${parkings} ${parkings === 1 ? 'parqueo' : 'parqueos'}` : null,
    `${area || 0} m²`,
  ].filter(Boolean).join(' · ');
}

export default function ProposalUnitChooser({ project }: { project: PortalProject }) {
  const [query, setQuery] = useState('');
  const [selected, setSelected] = useState<string[]>([]);
  const [activeSolarId, setActiveSolarId] = useState<string | null>(null);
  const [selectedSolarIds, setSelectedSolarIds] = useState<string[]>([]);
  const [solarTypologies, setSolarTypologies] = useState<Record<string, string>>({});
  // Ciprés always offers solar-first selection, even if its database type is
  // currently classified differently from a land subdivision.
  const solarFirst = Boolean(project.typologies?.length) && (project.slug === 'cipres-residences' || project.projectType === 'land_subdivision');
  const units = useMemo(() => project.units.filter((unit) => unit.status === 'Disponible'), [project.units]);
  const filtered = useMemo(() => units.filter((unit) => `${unit.unit} ${unit.type} ${unit.bedrooms || ''} ${unit.bathrooms || ''}`.toLowerCase().includes(query.toLowerCase())), [units, query]);
  const selectedSolar = units.find((unit) => unit.id === activeSolarId) || null;
  const typologies = project.typologies || [];
  const allSelectedHaveTypology = selectedSolarIds.length > 0 && selectedSolarIds.every((unitId) => Boolean(solarTypologies[unitId]));
  const href = solarFirst
    ? `/portal/proposals/new?project=${encodeURIComponent(project.slug)}&selections=${encodeURIComponent(selectedSolarIds.map((unitId) => `${unitId}:${solarTypologies[unitId]}`).filter((entry) => !entry.endsWith(':')).join(','))}`
    : `/portal/proposals/new?project=${encodeURIComponent(project.slug)}&units=${encodeURIComponent(selected.join(','))}`;

  if (solarFirst) return <div className="portal-enter mx-auto max-w-6xl space-y-6 py-4">
    <header className="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.18em] text-blue-600">{project.name}</p><h1 className="mt-2 text-2xl font-extrabold text-slate-950 sm:text-3xl"><LocalizedText text={"Selecciona solares y tipologías"} /></h1><p className="mt-2 text-sm text-slate-500"><LocalizedText text={"Primero selecciona los solares. Luego elige la tipología de cada uno."} /></p><p className="mt-2 text-xs font-bold text-slate-600">{selectedSolarIds.length} {selectedSolarIds.length === 1 ? 'solar seleccionado' : 'solares seleccionados'} · {selectedSolarIds.filter((id) => solarTypologies[id]).length}<LocalizedText text={" con tipología"} /></p></div><div className="flex shrink-0 items-center gap-2"><Link href="/portal/proposals/new" className="inline-flex h-10 items-center rounded-lg border border-slate-200 px-3 text-xs font-bold text-slate-600 hover:bg-slate-50"><LocalizedText text={"Cambiar unidad"} /></Link><Link href={href} aria-disabled={!allSelectedHaveTypology} className={`inline-flex h-10 items-center gap-2 rounded-lg px-4 text-xs font-bold text-white ${allSelectedHaveTypology ? 'bg-blue-600 hover:bg-blue-700' : 'pointer-events-none bg-slate-300'}`}><LocalizedText text={"Continuar "} /><ChevronRight className="h-4 w-4" /></Link></div></header>
    <div className="grid items-start gap-5 lg:grid-cols-[minmax(0,1.15fr)_minmax(330px,.85fr)]">
      <section className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-blue-50 text-xs font-black text-blue-700">1</span><div><h2 className="text-sm font-extrabold text-slate-900"><LocalizedText text={"1. Selecciona los solares"} /></h2><p className="text-xs text-slate-500"><LocalizedText text={"Marca todos los solares que incluirás en la propuesta."} /></p></div></div><div className="mt-4 flex items-center gap-2 rounded-xl border border-slate-200 px-3"><Search className="h-4 w-4 text-slate-400" /><UITranslationBoundary attributes={["placeholder"]}><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por solar, manzana o bloque" className="h-11 min-w-0 flex-1 text-sm outline-none" /></UITranslationBoundary></div><div className="mt-4 grid max-h-[590px] gap-3 overflow-y-auto pr-1 sm:grid-cols-2">{filtered.map((unit) => { const active = activeSolarId === unit.id; const selectedSolar = selectedSolarIds.includes(unit.id); const assigned = solarTypologies[unit.id]; const assignedTypology = typologies.find((item) => (item.key || item.id) === assigned || item.id === assigned); return <div key={unit.id} className={`flex items-center gap-2 rounded-xl border p-3 transition ${active ? 'border-blue-600 bg-blue-50 ring-2 ring-blue-100' : selectedSolar ? 'border-emerald-400 bg-emerald-50' : 'border-slate-200 hover:border-blue-300'}`}><button type="button" aria-pressed={selectedSolar} onClick={() => { setActiveSolarId(unit.id); setSelectedSolarIds((current) => current.includes(unit.id) ? current : [...current, unit.id]); }} className="flex min-w-0 flex-1 items-start justify-between p-1 text-left"><span><span className="block text-sm font-extrabold text-slate-900"><LocalizedText text={"Solar "} />{unit.unit}</span><span className="mt-1 block text-xs text-slate-500">{unit.tower && unit.tower !== 'Sin torre' ? unit.tower : 'Disponibilidad confirmable'}</span><span className="mt-3 block text-xs font-bold text-slate-700">{assignedTypology ? `Tipología: ${assignedTypology.name}` : selectedSolar ? <LocalizedText text={"Seleccionado · falta elegir tipología"} /> : <LocalizedText text={"Toca para seleccionar"} />}</span></span>{selectedSolar && <span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-blue-600 text-white"><Check className="h-4 w-4" /></span>}</button>{selectedSolar && <button type="button" onClick={() => { setSelectedSolarIds((current) => current.filter((id) => id !== unit.id)); setSolarTypologies((current) => { const next = { ...current }; delete next[unit.id]; return next; }); if (activeSolarId === unit.id) setActiveSolarId(null); }} className="rounded-lg px-2 py-1 text-[11px] font-bold text-slate-500 hover:bg-white hover:text-slate-900"><LocalizedText text={"Quitar"} /></button>}</div>})}</div></section>
      <section className="sticky top-4 rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-blue-50 text-xs font-black text-blue-700">2</span><div><h2 className="text-sm font-extrabold text-slate-900"><LocalizedText text={"2. Asigna la tipología"} /></h2><p className="text-xs text-slate-500">{selectedSolar ? `Elige la tipología del Solar ${selectedSolar.unit}.` : <LocalizedText text={"Primero selecciona un solar en la lista."} />}</p></div></div>{selectedSolar && selectedSolarIds.includes(selectedSolar.id) ? <div className="mt-4 space-y-3">{typologies.map((typology) => { const key = typology.key || typology.id; const active = solarTypologies[selectedSolar.id] === key || solarTypologies[selectedSolar.id] === typology.id; const price = typologyPrice(selectedSolar, typology); return <button key={typology.id} type="button" onClick={() => setSolarTypologies((current) => ({ ...current, [selectedSolar.id]: key }))} className={`flex w-full items-start justify-between rounded-xl border p-4 text-left transition ${active ? 'border-blue-600 bg-blue-50 ring-2 ring-blue-100' : 'border-slate-200 hover:border-blue-300'}`}><div><p className="text-sm font-extrabold text-slate-900">{typology.name}</p><p className="mt-1 text-sm font-bold text-blue-700">{formatCurrency(price, selectedSolar.currency || project.currency || 'USD')}</p><p className="mt-3 text-xs text-slate-500">{unitSummary({ bedrooms: typology.bedrooms, bathrooms: typology.bathrooms, parkingSpaces: typology.parkingSpaces, area: typology.totalSqm })}</p></div>{active && <span className="grid h-6 w-6 place-items-center rounded-full bg-blue-600 text-white"><Check className="h-4 w-4" /></span>}</button>})}</div> : <div className="mt-5 rounded-xl border border-dashed border-slate-200 bg-slate-50 p-8 text-center text-xs text-slate-500"><LocalizedText text={"Selecciona primero un solar. Después podrás asignarle su tipología."} /></div>}</section>
    </div>
  </div>;

  return <div className="portal-enter mx-auto max-w-5xl space-y-6 py-4"><header className="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.18em] text-blue-600">{project.name}</p><h1 className="mt-2 text-2xl font-extrabold text-slate-950 sm:text-3xl"><LocalizedText text={"Selecciona las unidades"} /></h1><p className="mt-2 text-sm text-slate-500"><LocalizedText text={"Puedes incluir una o varias unidades del mismo proyecto. El contenido oficial se prepara automáticamente."} /></p></div><div className="flex shrink-0 items-center gap-2"><Link href="/portal/proposals/new" className="inline-flex h-10 items-center rounded-lg border border-slate-200 px-3 text-xs font-bold text-slate-600 hover:bg-slate-50"><LocalizedText text={"Cambiar unidad"} /></Link><Link href={href} aria-disabled={selected.length === 0} className={`inline-flex h-10 items-center rounded-lg px-4 text-xs font-bold text-white ${selected.length ? 'bg-blue-600 hover:bg-blue-700' : 'pointer-events-none bg-slate-300'}`}><LocalizedText text={"Continuar "} />{selected.length ? `(${selected.length})` : ''}</Link></div></header><div className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3"><Search className="h-4 w-4 text-slate-400" /><UITranslationBoundary attributes={["placeholder"]}><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por unidad, habitaciones o baños" className="h-11 min-w-0 flex-1 text-sm outline-none" /></UITranslationBoundary></div><div className="grid gap-3 md:grid-cols-2">{filtered.map((unit) => { const active = selected.includes(unit.id); return <button key={unit.id} type="button" onClick={() => setSelected((current) => active ? current.filter((id) => id !== unit.id) : [...current, unit.id])} className={`flex items-start justify-between rounded-xl border p-4 text-left transition ${active ? 'border-blue-600 bg-blue-50 ring-2 ring-blue-100' : 'border-slate-200 bg-white hover:border-blue-300'}`}><div><p className="text-sm font-extrabold text-slate-900"><LocalizedText text={"Unidad "} />{unit.unit}</p><p className="mt-1 text-sm font-bold text-blue-700">{formatCurrency(unit.price, unit.currency || 'USD')}</p><p className="mt-3 text-xs text-slate-500">{unitSummary({ bedrooms: unit.bedrooms, bathrooms: unit.bathrooms, parkingSpaces: Number(unit.customColumns?.PARQUEOS || unit.customColumns?.Parqueos || unit.customColumns?.parkings || unit.customColumns?.parking || 0), area: unit.area || Number(unit.customColumns?.['METROS CUADRADOS'] || unit.customColumns?.construction_sqm || 0) })}</p></div>{active && <span className="grid h-6 w-6 place-items-center rounded-full bg-blue-600 text-white"><Check className="h-4 w-4" /></span>}</button>})}</div></div>;
}
