import assert from 'node:assert/strict';
import { advanceWorkflow, emptyWorkflow, updateWorkflowDeal, createWorkflowContact, readWorkflow, PAYMENT_DELAY_MS, PROFORMA_DELAY_MS, COMMISSION_DELAY_MS, type WorkflowDeal } from '../lib/demo/browser-workflow';

process.env.NEXT_PUBLIC_APP_SCOPE = 'demo';
const storage = new Map<string, string>();
Object.assign(globalThis, { window: { localStorage: { getItem: (key: string) => storage.get(key), setItem: (key: string, value: string) => storage.set(key, value) }, dispatchEvent: () => true } });
const form = new FormData(); form.set('name', 'Lucía Ventura'); form.set('phone', '8095550142'); form.set('email', 'lucia@horizonte.example'); form.set('budgetMax', '380000');
const contact = createWorkflowContact(form);
assert.equal(readWorkflow().contacts[0].id, contact.id);
assert.equal(contact.primaryOpportunity?.budgetMax, 380000);
const start = Date.parse('2026-10-08T12:00:00Z');
const deal: WorkflowDeal = { id: '123456789', contactId: contact.id, contactCode: contact.publicCode, clientName: contact.fullName, projectId: 9401, projectSlug: 'villas-bahia-coral', projectName: 'Villas Bahía Coral', developer: 'Desarrollos Costa Serena', unitId: '940101', unitCode: 'BA-01', price: 380000, currency: 'USD', commissionRate: 5, reservedAt: new Date(start).toISOString() };
const state = emptyWorkflow(); state.deals.push(deal);
storage.set('ob-demo.workflow.v1', JSON.stringify(state));
assert.throws(() => updateWorkflowDeal(deal.id, 'invoice'), /aprobada/);
assert.throws(() => updateWorkflowDeal(deal.id, 'request_claim'), /confirmación/);
assert.throws(() => updateWorkflowDeal(deal.id, 'report_payment', { amount: 380001 }), /monto/);
deal.paymentReportedAt = new Date(start).toISOString();
assert.equal(advanceWorkflow(state, start + PAYMENT_DELAY_MS - 1), false);
assert.equal(advanceWorkflow(state, start + PAYMENT_DELAY_MS), true);
assert.equal(deal.paymentConfirmedAt, deal.promiseSignedAt);
deal.claimRequestedAt = deal.paymentConfirmedAt; deal.proformaAt = deal.paymentConfirmedAt;
const reloaded = JSON.parse(JSON.stringify(state));
assert.equal(advanceWorkflow(reloaded, start + PAYMENT_DELAY_MS + PROFORMA_DELAY_MS - 1), false);
assert.equal(advanceWorkflow(reloaded, start + PAYMENT_DELAY_MS + PROFORMA_DELAY_MS), true);
reloaded.deals[0].invoiceAt = reloaded.deals[0].proformaApprovedAt;
assert.equal(advanceWorkflow(reloaded, start + PAYMENT_DELAY_MS + PROFORMA_DELAY_MS + COMMISSION_DELAY_MS), true);
assert.ok(reloaded.deals[0].paidAt);
assert.equal(advanceWorkflow(reloaded, start + 999999), false);
console.log('Browser workflow: creation, ordering, exact delays and reload passed.');
