alter table public.projects
  add column if not exists external_availability_url text
  check (external_availability_url is null or external_availability_url ~ '^https://');

comment on column public.projects.external_availability_url is
  'Optional external availability page. It is a link only; canonical units are imported separately.';

-- Remove only the accidental starter inventory generated by the old fallback
-- for UVE. Real inventory with other codes or typologies is preserved.
do $$
declare
  target_project_id bigint;
begin
  select id into target_project_id
  from public.projects
  where lower(name) like '%uve%residence%'
  order by created_at desc
  limit 1;

  if target_project_id is not null then
    update public.projects
    set external_availability_url = 'https://brokers.alterestate.com/disponibilidad/uve-residence-1'
    where id = target_project_id;

    delete from public.units
    where project_id = target_project_id
      and unit_code in ('A-101','A-102','A-103','A-104','A-201','A-202','A-203','A-204','PH-301','PH-302')
      and typology_id in (
        select id from public.typologies
        where project_id = target_project_id
          and name = 'Suite 2 Habitaciones Golf View'
      );

    -- The previous importer treated AlterEstate HTML/CSS as CSV. Remove only
    -- rows that clearly contain CSS fragments or invalid scraped labels.
    delete from public.units
    where project_id = target_project_id
      and (
        unit_code like '%:%'
        or lower(unit_code) like 'top%'
        or lower(unit_code) like 'width%'
        or lower(unit_code) like '%transform%'
        or lower(unit_code) like 'border-radius%'
      );

    delete from public.typologies t
    where t.project_id = target_project_id
      and t.name = 'Suite 2 Habitaciones Golf View'
      and not exists (select 1 from public.units u where u.typology_id = t.id);

    update public.projects
    set inventory_total_declared = 0,
        inventory_available_declared = 0,
        inventory_updated_at = now()
    where id = target_project_id
      and not exists (select 1 from public.units u where u.project_id = target_project_id);
  end if;
end $$;
